import './globals.css'
import ProviderPage  from './Provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl">
      <body >
        <ProviderPage children={children}/>
        <div  className="navigation-hidden"></div>
        </body>
    </html>
  )
}
